# Configuration for local development
---
port: 8443
webhook-secret-file: secrets/github-webhook-secret.txt
firebase-auth-file: secrets/firebase-auth.json

# GitHub Integration auth info
integration:
  id-file: secrets/integration-id.txt
  key-file: secrets/integration.pkcs8

database:
  driver-class: org.postgresql.Driver
  jdbc-url: jdbc:postgresql://localhost:5432/preview_code
  username: admin
  password: password

  connection-pool:
    partition-count: 4
    min-connections-per-partition: 1
    max-connections-per-partition: 10